# Generated by Django 3.1.5 on 2021-01-07 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20210107_0044'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ['-update_on']},
        ),
        migrations.AddField(
            model_name='profile',
            name='update_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
